# Generated by Django 3.0.5 on 2020-05-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatStoreApp', '0002_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.CharField(blank=True, choices=[('drumKit', 'drumKit'), ('midiKit', 'midiKit'), ('samplePack', 'samplePack'), ('preset', 'preset'), ('dawPlugin', 'dawPlugin'), ('tutorial', 'tutorial')], max_length=30, null=True),
        ),
    ]
