# Generated by Django 3.0.5 on 2020-05-31 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beatStoreApp', '0004_subscribe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
