# Generated by Django 3.0.5 on 2020-05-31 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatStoreApp', '0005_delete_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Phone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
