# Generated by Django 3.0.5 on 2020-06-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatStoreApp', '0006_auto_20200531_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='link2',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='linkTitle1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='linkTitle2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
