# Generated by Django 3.0.5 on 2020-06-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatStoreApp', '0007_auto_20200601_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='link2',
            field=models.URLField(blank=True, max_length=220, null=True),
        ),
    ]
