# Generated by Django 3.0.5 on 2020-06-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatStoreApp', '0008_auto_20200601_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Title',
            field=models.CharField(max_length=250),
        ),
    ]
