# Generated by Django 3.0.5 on 2020-06-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatStoreApp', '0009_auto_20200606_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='btnColor',
            field=models.CharField(blank=True, choices=[('color1', 'color 1'), ('color2', 'color 2'), ('color3', 'color 3')], max_length=30, null=True),
        ),
    ]
