# Generated by Django 3.0.5 on 2020-06-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatStoreApp', '0012_auto_20200614_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='btnColor',
            field=models.CharField(blank=True, choices=[('color1', 'greenColor'), ('color2', 'purpleColor'), ('color3', 'pinkColor')], default='purpleColor', max_length=30, null=True),
        ),
    ]
