# Generated by Django 3.0.5 on 2020-06-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatStoreApp', '0013_auto_20200614_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='btnColor',
            field=models.CharField(blank=True, choices=[('greenColor', 'greenColor'), ('purpleColor', 'purpleColor'), ('pinkColor', 'pinkColor')], default='purpleColor', max_length=30, null=True),
        ),
    ]
