# Generated by Django 3.0.5 on 2020-06-14 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beatStoreApp', '0014_auto_20200614_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='btnColor',
        ),
    ]
