# Generated by Django 3.0.5 on 2020-06-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatStoreApp', '0015_remove_product_btncolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='youtubeEmbed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
