# Generated by Django 3.0.5 on 2020-06-18 18:42

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beatStoreApp', '0016_product_youtubeembed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('drumKit', 'drumKit'), ('midiKit', 'midiKit'), ('samplePack', 'samplePack'), ('preset', 'preset'), ('dawPlugin', 'dawPlugin'), ('tutorial', 'tutorial')], max_length=52, null=True),
        ),
    ]
