# Generated by Django 3.0.5 on 2020-06-18 18:43

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beatStoreApp', '0017_auto_20200618_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Category2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('drumKit', 'drumKit'), ('midiKit', 'midiKit'), ('samplePack', 'samplePack'), ('preset', 'preset'), ('dawPlugin', 'dawPlugin'), ('tutorial', 'tutorial')], max_length=52, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.CharField(blank=True, choices=[('drumKit', 'drumKit'), ('midiKit', 'midiKit'), ('samplePack', 'samplePack'), ('preset', 'preset'), ('dawPlugin', 'dawPlugin'), ('tutorial', 'tutorial')], max_length=30, null=True),
        ),
    ]
