# Generated by Django 3.0.5 on 2020-06-18 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beatStoreApp', '0018_auto_20200618_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category2',
            new_name='multipleCategory',
        ),
    ]
