# Generated by Django 3.0.5 on 2020-06-18 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beatStoreApp', '0020_remove_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='multipleCategory',
            new_name='Category',
        ),
    ]
